version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
shallow_clone: true
before_build:
- cmd: nuget restore src\OnlineAfspraken.sln
build:
  verbosity: minimal
test: off
artifacts:
- path: src\OnlineAfspraken\bin\Release\*.nupkg